### ISSUE TITLE
is_voted 함수 호출 시 401을 반환하는 문제

### ISSUE THREAD

**Issue by Craphting** [koreanbots/py-sdk#27]
![image](https://user-images.githubusercontent.com/46986283/131327968-52582381-1cd5-4ef2-b5a1-fee1a3dd2d65.png)
로그인이 필요하다는 문구가 출력됩니다. API 키를 재발급해 다시 시도해보았으나 여전히 같은 오류를 반환하고 있습니다.
koreanbots 모듈은 1.1.2 최신 버전을 사용 중입니다.

**Comment by Craphting** [comment]
_bot.koreanbots 오브젝트는 이렇습니다.
![image](https://user-images.githubusercontent.com/46986283/131328132-3d42ede5-c4ea-4f52-9bdc-e5079bcddb25.png)

**Comment by SaidBySolo** [comment]
https://github.com/koreanbots/py-sdk/blob/8c14bf4bab94ccfe371706e543a019c33bfd7eb7/koreanbots/http.py#L245-L246
