### ISSUE TITLE
discord.py 개발 종료에 따른 라이브러리 변경

### ISSUE THREAD

**Issue by MisileLab** [koreanbots/py-sdk#29]
discord.py 개발자가 개발 종료를 하고 리포지토리를 archive 했습니다. 이에 따라 discord.py가 아닌 다른 라이브러리를 쓰는 것을 권합니다.
라이브러리 추천
https://github.com/discord-pyc/discord.pyc
https://github.com/EQUENOS/disnake

**Comment by SaidBySolo** [comment]
실질적인 기능에 영향이없습니다.
