### ISSUE TITLE
Supporting v2 API

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/py-sdk#4]
# Should support v2 API(GraphQL) before v2 release.

Working at #6

### BaseURL
Beta(For now):

```
beta.koreanbots.dev/api
```

Production
```
koreanbots.dev/api
```

### Document

https://github.com/koreanbots/api-docs

## To-do

- [ ] Get User
- [ ] Get Bot
- [ ] Update Server

**Comment by kijk2869** [comment]
I'm busy because of youtube-dl takedown.

**Comment by wonderlandpark** [comment]
> I'm busy because of youtube-dl takedown.

Removed Comment as `off-topic`

**Comment by wonderlandpark** [comment]
# RestAPI

### BaseURL
Beta(For now):

```
api.beta.koreanbots.dev
```

Production
```
api.koreanbots.dev
```

## `PATCH` /v2/bots/:id

### Body

```json
{ "servers": 1000 }
```

**Comment by kijk2869** [comment]
will use `graphql`

**Comment by wonderlandpark** [comment]
?

**Comment by ReDesignedJP** [comment]
lol

**Comment by SaidBySolo** [comment]
lel

**Comment by ReDesignedJP** [comment]
Get User In**__t__**o

**Comment by wonderlandpark** [comment]
Locking Issue as off-topic

**Comment by wonderlandpark** [comment]
This issue is due to `2020-11-1`

**Comment by wonderlandpark** [comment]
`Server Update` Due to `2020-11-07`

**Comment by wonderlandpark** [comment]
@kijk2869 Added Docs

**Comment by kijk2869** [comment]
https://github.com/koreanbots/py-sdk/pull/6
